version: '3.8'

services:
  backend:
    build: .
    container_name: rag-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - APP_MODE=production
      # Add other env vars as needed
    volumes:
      - .:/app

  frontend:
    image: node:20
    container_name: rag-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend 